export const ALL_PICTURES = "ALL_PICTURES";
export const START_LOADING = "START_LOADING";
export const FAILD_LOADIN_PICTURES = "FAILD_LOADIN_PICTURES";
export const SUCCESUFULY_LOADED_PICTURES = "SUCCESUFULY_LOADED_PICTURES";