export const START_LOADING_PICTURES = "START_LOADING_PICTURES";
export const FAILD_LOADIN_PICTURES = "FAILD_LOADIN_PICTURES";
export const SUCCESUFULY_LOADED_PICTURES = "SUCCESUFULY_LOADED_PICTURES";


export const START_LOADING_PICTURE_REVIEWS = "START_LOADING_PICTURE_REVIEWS";
export const SUCCESUFULY_LOADED_PICTURE_REVIEWS = "SUCCESUFULY_LOADED_PICTURE_REVIEWS";
export const START_LOADING_PICTURE = "START_LOADING_PICTURE"
export const SUCCESSFULLY_CREATED_REVIEW = "SUCCESSFULLY_CREATED_REVIEW";


export const SUCCESSFULLY_CREATED_USER = "SUCCESSFULLY_CREATED_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const START_LOADING_PICTURES_USER = "START_LOADING_PICTURES_USER";
export const SUCCESSFUL_LOADING_PICTURES_USER = "SUCCESSFUL_LOADING_PICTURES_USER";