export const START_LOADING_PICTURES = "START_LOADING_PICTURES";
export const FAILD_LOADIN_PICTURES = "FAILD_LOADIN_PICTURES";
export const SUCCESUFULY_LOADED_PICTURES = "SUCCESUFULY_LOADED_PICTURES";


export const START_LOADING_PICTURE_REVIEWS = "START_LOADING_PICTURE_REVIEWS";
export const SUCCESUFULY_LOADED_PICTURE_REVIEWS = "SUCCESUFULY_LOADED_PICTURE_REVIEWS";
export const START_LOADING_PICTURE = "START_LOADING_PICTURE"


